# Generated by Django 2.2.4 on 2019-09-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category1', models.CharField(max_length=120)),
                ('category2', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=120)),
                ('weight', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('material', models.CharField(max_length=120)),
                ('volume', models.CharField(max_length=10)),
                ('print_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
