# Generated by Django 2.2.4 on 2019-09-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='category2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='print_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
