# Generated by Django 2.2.4 on 2019-09-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190901_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
